name: Deploy Static App to Azure

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: voiceai.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 3: Build and tag the Docker image with the latest Git commit hash
      - name: Build and Tag Docker Image
        run: |
          COMMIT_HASH=$(echo ${{ github.sha }})
          docker build -t voiceai.azurecr.io/voice-ai-client:$COMMIT_HASH .
          echo "Docker image tagged as voiceai.azurecr.io/voice-ai-client:$COMMIT_HASH"

      # Step 4: Push the Docker image to ACR
      - name: Push Docker Image to ACR
        run: |

          COMMIT_HASH=$(echo ${{ github.sha }})
          docker push voiceai.azurecr.io/voice-ai-client:$COMMIT_HASH

      # Step 5: Deploy the updated image to Azure App Service
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: voice-ai-client
          slot-name: production
          images: |
            voiceai.azurecr.io/voice-ai-client:${{ github.sha }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
